name: Release
on:
  workflow_run:
    workflows: ['Tests']
    branches: [main]
    types:
      - completed
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPMJS_METACOMMERCE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_METACOMMERCE_TOKEN }}
        run: |
          npx semantic-release
